main: me.Loikas.ExpandedEnchants.Main
name: ExpandedEnchants
description: More enchants and improved vanilla system
author: Loikas
api-version: 1.17
version: 1.7
softdepend:
- Vault
commands:
    expandedenchants:
        description: All expandedenchant commands
        usage: "Usage /<command>  <give|reload|enchant|recipes>  <enchant> [level]"
        aliases: ee
permissions:
    ee.command.buy.*:
        description: Allows you to use the '/ee buy' command to enchant your item using money.
        default: op
    ee.command.cost:
        description: Allows you to use the '/ee cost' command to see what a package would cost.
        default: true
    ee.command.repair:
        description: Allows you to use the '/ee repair' command to repair your item using money.
        default: true
    ee.command.creative:
        description: Allows for easier creative mode by using '/ee'
        default: op
    ee.command.reload:
        description: Reloads the config file
        default: op
    ee.command.enchant:
        description: Allows you to enchant items using the command
        default: op
    ee.command.give:
        description: Allows you to give yourself custom enchantment books
        default: op
    ee.command.hideenchants:
        description: Allows you to hide the custom enchants on your item using /ee hideenchants [true|false]
        default: op